// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyThuVien_UNETI04_DHTI17A1ND.Data;

#nullable disable

namespace QuanLyThuVien_UNETI04_DHTI17A1ND.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyThuVien_UNETI04_DHTI17A1ND.Models.Entities.ChiTietPhieuMuon", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTiet"));

                    b.Property<int>("MaPhieuMuon")
                        .HasColumnType("int");

                    b.Property<int>("MaSach")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTra")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuongMuon")
                        .HasColumnType("int");

                    b.Property<string>("TinhTrangTra")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaChiTiet");

                    b.HasIndex("MaPhieuMuon");

                    b.HasIndex("MaSach");

                    b.ToTable("ChiTietPhieuMuon");
                });

            modelBuilder.Entity("QuanLyThuVien_UNETI04_DHTI17A1ND.Models.Entities.DocGia", b =>
                {
                    b.Property<int>("MaDocGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDocGia"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaDocGia");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique();

                    b.ToTable("DocGia");
                });

            modelBuilder.Entity("QuanLyThuVien_UNETI04_DHTI17A1ND.Models.Entities.PhieuMuon", b =>
                {
                    b.Property<int>("MaPhieuMuon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuMuon"));

                    b.Property<DateTime>("HanTra")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaDocGia")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayMuon")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaPhieuMuon");

                    b.HasIndex("MaDocGia");

                    b.ToTable("PhieuMuon");
                });

            modelBuilder.Entity("QuanLyThuVien_UNETI04_DHTI17A1ND.Models.Entities.Sach", b =>
                {
                    b.Property<int>("MaSach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSach"));

                    b.Property<decimal>("GiaSach")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaTheLoai")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("NamXuatBan")
                        .HasColumnType("int");

                    b.Property<string>("NhaXuatBan")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongCon")
                        .HasColumnType("int");

                    b.Property<string>("TacGia")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TenSach")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaSach");

                    b.HasIndex("MaTheLoai");

                    b.ToTable("Sach");
                });

            modelBuilder.Entity("QuanLyThuVien_UNETI04_DHTI17A1ND.Models.Entities.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyThuVien_UNETI04_DHTI17A1ND.Models.Entities.TheLoai", b =>
                {
                    b.Property<int>("MaTheLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTheLoai"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenTheLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaTheLoai");

                    b.HasIndex("TenTheLoai")
                        .IsUnique();

                    b.ToTable("TheLoai");
                });

            modelBuilder.Entity("QuanLyThuVien_UNETI04_DHTI17A1ND.Models.Entities.ChiTietPhieuMuon", b =>
                {
                    b.HasOne("QuanLyThuVien_UNETI04_DHTI17A1ND.Models.Entities.PhieuMuon", "PhieuMuon")
                        .WithMany("ChiTietPhieuMuons")
                        .HasForeignKey("MaPhieuMuon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyThuVien_UNETI04_DHTI17A1ND.Models.Entities.Sach", "Sach")
                        .WithMany("ChiTietPhieuMuons")
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhieuMuon");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("QuanLyThuVien_UNETI04_DHTI17A1ND.Models.Entities.DocGia", b =>
                {
                    b.HasOne("QuanLyThuVien_UNETI04_DHTI17A1ND.Models.Entities.TaiKhoan", "TaiKhoan")
                        .WithOne("DocGia")
                        .HasForeignKey("QuanLyThuVien_UNETI04_DHTI17A1ND.Models.Entities.DocGia", "MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyThuVien_UNETI04_DHTI17A1ND.Models.Entities.PhieuMuon", b =>
                {
                    b.HasOne("QuanLyThuVien_UNETI04_DHTI17A1ND.Models.Entities.DocGia", "DocGia")
                        .WithMany("PhieuMuons")
                        .HasForeignKey("MaDocGia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DocGia");
                });

            modelBuilder.Entity("QuanLyThuVien_UNETI04_DHTI17A1ND.Models.Entities.Sach", b =>
                {
                    b.HasOne("QuanLyThuVien_UNETI04_DHTI17A1ND.Models.Entities.TheLoai", "TheLoai")
                        .WithMany("Sachs")
                        .HasForeignKey("MaTheLoai")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TheLoai");
                });

            modelBuilder.Entity("QuanLyThuVien_UNETI04_DHTI17A1ND.Models.Entities.DocGia", b =>
                {
                    b.Navigation("PhieuMuons");
                });

            modelBuilder.Entity("QuanLyThuVien_UNETI04_DHTI17A1ND.Models.Entities.PhieuMuon", b =>
                {
                    b.Navigation("ChiTietPhieuMuons");
                });

            modelBuilder.Entity("QuanLyThuVien_UNETI04_DHTI17A1ND.Models.Entities.Sach", b =>
                {
                    b.Navigation("ChiTietPhieuMuons");
                });

            modelBuilder.Entity("QuanLyThuVien_UNETI04_DHTI17A1ND.Models.Entities.TaiKhoan", b =>
                {
                    b.Navigation("DocGia");
                });

            modelBuilder.Entity("QuanLyThuVien_UNETI04_DHTI17A1ND.Models.Entities.TheLoai", b =>
                {
                    b.Navigation("Sachs");
                });
#pragma warning restore 612, 618
        }
    }
}
